version: '3'
services:
  integration-map:
    container_name: integration-map
    build:
      context: .
    ports: 
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
volumes:
  forcegrapher: {}
